from typing import Iterator

from smg.pyopencv import CVMat1d, CVMat1f, CVMat3b


def temp(imu_points) -> None: ...

# CLASSES

class IMUPoint:
	def __init__(self, acc_x: float, acc_y: float, acc_z: float, ang_vel_x: float, ang_vel_y: float, ang_vel_z: float, timestamp: float): ...

class IMUPoints:
	def __iter__(self) -> Iterator[IMUPoint]: ...
	def __len__(self) -> int: ...
	def __repr__(self) -> str: ...
	def append(self, elt: IMUPoint) -> None: ...

class System:
	def __init__(self, voc_file: str, settings_file: str, sensor: ESensor, use_viewer: bool): ...
	def shutdown(self) -> None: ...
	def track_monocular(self, im: CVMat3b, timestamp: float) -> CVMat1d: ...
	def track_rgbd(self, im: CVMat3b, depthmap: CVMat1f, timestamp: float) -> CVMat1d: ...

# ENUMERATIONS

class ESensor(int):
	pass

MONOCULAR: ESensor
STEREO: ESensor
RGBD: ESensor
