####################
# LinkOpenNI.cmake #
####################


TARGET_LINK_LIBRARIES(${targetname} PRIVATE ${OPENNI_LIBRARY})

IF(WIN32)
  SET(OPENNI_RUNTIMELIBS "${OPENNI_ROOT}/Redist/OpenNI2.dll")
ENDIF()

FOREACH(RUNTIMELIB ${OPENNI_RUNTIMELIBS})
  ADD_CUSTOM_COMMAND(TARGET ${targetname} POST_BUILD COMMAND ${CMAKE_COMMAND} -E copy_if_different ${RUNTIMELIB} "$<TARGET_FILE_DIR:${targetname}>")
ENDFOREACH()
