###################
# UseOpenCV.cmake #
###################

FIND_PACKAGE(OpenCV 3.4.12 REQUIRED HINTS "$ENV{HOMEDRIVE}$ENV{HOMEPATH}/Downloads/opencv-3.4.12/build")
INCLUDE_DIRECTORIES(BEFORE SYSTEM ${OpenCV_INCLUDE_DIRS})
ADD_DEFINITIONS(-DWITH_OPENCV)
